const tableData = [
  {
    UserId: 1,
    UserImg: '../../Assets/Images/profile/user/small/1.jpg',
    UserName: 'مهـرداد خضـریـان  |  Mehrdad Khezrian',
    Location: 'تهـران  |  Tehran',
    MainInstrument: 'گیـتـار  |  Guitar',
    Level: { title: 'مبتدی  |  Beginner', LevelNumber: 0 },
    Style: 'کـلاسیـک  |  Classical',
  },
  {
    UserId: 2,
    UserImg: null,
    UserName: 'مهـرداد خضـریـان  |  Mehrdad Khezrian',
    Location: 'تهـران  |  Tehran',
    MainInstrument: 'گیـتـار  |  Guitar',
    Level: { title: 'مبتدی  |  Beginner', LevelNumber: 1 },
    Style: 'کـلاسیـک  |  Classical',
  },
  {
    UserId: 3,
    UserImg: null,
    UserName: 'مهـرداد خضـریـان  |  Mehrdad Khezrian',
    Location: 'تهـران  |  Tehran',
    MainInstrument: 'گیـتـار  |  Guitar',
    Level: { title: 'مبتدی  |  Beginner', LevelNumber: 2 },
    Style: 'کـلاسیـک  |  Classical',
  },
  {
    UserId: 4,
    UserImg: null,
    UserName: 'مهـرداد خضـریـان  |  Mehrdad Khezrian',
    Location: 'تهـران  |  Tehran',
    MainInstrument: 'گیـتـار  |  Guitar',
    Level: { title: 'مبتدی  |  Beginner', LevelNumber: 3 },
    Style: 'کـلاسیـک  |  Classical',
  },
  {
    UserId: 5,
    UserImg: null,
    UserName: 'مهـرداد خضـریـان  |  Mehrdad Khezrian',
    Location: 'تهـران  |  Tehran',
    MainInstrument: 'گیـتـار  |  Guitar',
    Level: { title: 'مبتدی  |  Beginner', LevelNumber: 3 },
    Style: 'کـلاسیـک  |  Classical',
  },
  {
    UserId: 6,
    UserImg: null,
    UserName: 'مهـرداد خضـریـان  |  Mehrdad Khezrian',
    Location: 'تهـران  |  Tehran',
    MainInstrument: 'گیـتـار  |  Guitar',
    Level: { title: 'مبتدی  |  Beginner', LevelNumber: 3 },
    Style: 'کـلاسیـک  |  Classical',
  },
  {
    UserId: 7,
    UserImg: null,
    UserName: 'مهـرداد خضـریـان  |  Mehrdad Khezrian',
    Location: 'تهـران  |  Tehran',
    MainInstrument: 'گیـتـار  |  Guitar',
    Level: { title: 'مبتدی  |  Beginner', LevelNumber: 3 },
    Style: 'کـلاسیـک  |  Classical',
  },
  {
    UserId: 8,
    UserImg: null,
    UserName: 'مهـرداد خضـریـان  |  Mehrdad Khezrian',
    Location: 'تهـران  |  Tehran',
    MainInstrument: 'گیـتـار  |  Guitar',
    Level: { title: 'مبتدی  |  Beginner', LevelNumber: 3 },
    Style: 'کـلاسیـک  |  Classical',
  },
  {
    UserId: 9,
    UserImg: null,
    UserName: 'مهـرداد خضـریـان  |  Mehrdad Khezrian',
    Location: 'تهـران  |  Tehran',
    MainInstrument: 'گیـتـار  |  Guitar',
    Level: { title: 'مبتدی  |  Beginner', LevelNumber: 3 },
    Style: 'کـلاسیـک  |  Classical',
  },
  {
    UserId: 10,
    UserImg: null,
    UserName: 'مهـرداد خضـریـان  |  Mehrdad Khezrian',
    Location: 'تهـران  |  Tehran',
    MainInstrument: 'گیـتـار  |  Guitar',
    Level: { title: 'مبتدی  |  Beginner', LevelNumber: 3 },
    Style: 'کـلاسیـک  |  Classical',
  },
]
export { tableData }
